// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_E8JfmScnhsxqW-sBCOfW8kRFdNcrGIk',
    appId: '1:380453135946:web:00e83d9df74b17c19ba8b3',
    messagingSenderId: '380453135946',
    projectId: 'campuspulse-bfd09',
    authDomain: 'campuspulse-bfd09.firebaseapp.com',
    storageBucket: 'campuspulse-bfd09.firebasestorage.app',
    measurementId: 'G-Z88LVC6TST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBjjl6EAyTBDtCBeeZxppJhhmCGHEVyt8',
    appId: '1:380453135946:android:c2ba47919d87bc7f9ba8b3',
    messagingSenderId: '380453135946',
    projectId: 'campuspulse-bfd09',
    storageBucket: 'campuspulse-bfd09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsqXZprKryEPVbp5Dv4ebg4c1eJQ0NAsQ',
    appId: '1:380453135946:ios:a5426b1f1cd654379ba8b3',
    messagingSenderId: '380453135946',
    projectId: 'campuspulse-bfd09',
    storageBucket: 'campuspulse-bfd09.firebasestorage.app',
    iosBundleId: 'com.example.campuspulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsqXZprKryEPVbp5Dv4ebg4c1eJQ0NAsQ',
    appId: '1:380453135946:ios:a5426b1f1cd654379ba8b3',
    messagingSenderId: '380453135946',
    projectId: 'campuspulse-bfd09',
    storageBucket: 'campuspulse-bfd09.firebasestorage.app',
    iosBundleId: 'com.example.campuspulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_E8JfmScnhsxqW-sBCOfW8kRFdNcrGIk',
    appId: '1:380453135946:web:2cb8d7a5444ab01e9ba8b3',
    messagingSenderId: '380453135946',
    projectId: 'campuspulse-bfd09',
    authDomain: 'campuspulse-bfd09.firebaseapp.com',
    storageBucket: 'campuspulse-bfd09.firebasestorage.app',
    measurementId: 'G-3RXR1L31L1',
  );

}