import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:campuspulse/modules/auth/login_page.dart';
import 'package:campuspulse/modules/auth/register_page.dart';
import 'package:campuspulse/modules/auth/email_verification_page.dart';
import 'package:campuspulse/modules/home/home_page.dart';
import 'package:campuspulse/core/splash_screen.dart'; 

// 1. This file is generated by 'flutterfire configure'
import 'firebase_options.dart'; 

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // 2. Initialize Firebase using the generated options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  runApp(const CampusPulse());
}

class CampusPulse extends StatelessWidget {
  const CampusPulse({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'CampusPulse',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        // UniKL Colors
        primaryColor: const Color(0xFF104C97), // UniKL Blue
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF104C97),
          secondary: const Color(0xFFF0AB00), // UniKL Yellow/Orange
        ),
        useMaterial3: true,
        inputDecorationTheme: InputDecorationTheme(
          border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
          filled: true,
          fillColor: Colors.grey.shade50,
        ),
      ),

      initialRoute: '/splash', 
      routes: {
        '/splash': (context) => const SplashScreen(), 
        '/landing': (context) => const LandingPage(),
        '/login': (context) => const LoginPage(),
        '/register': (context) => const RegisterPage(),
        '/verify_email': (context) => const EmailVerificationPage(),
        '/home': (context) => const HomePage(),
      },
    );
  }
}

class LandingPage extends StatelessWidget {
  const LandingPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: Padding(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(Icons.directions_bus_filled, size: 80, color: Color(0xFF104C97)),
            const SizedBox(height: 20),
            const Text(
              "CampusPulse",
              style: TextStyle(
                fontSize: 32,
                fontWeight: FontWeight.bold,
                color: Color(0xFF104C97),
              ),
            ),
            const SizedBox(height: 10),
            const Text(
              "Smart Shuttle for UniKL Students",
              style: TextStyle(fontSize: 16, color: Colors.grey),
            ),
            const SizedBox(height: 50),
            SizedBox(
              width: double.infinity,
              height: 50,
              child: ElevatedButton(
                onPressed: () => Navigator.pushNamed(context, '/login'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF104C97),
                  foregroundColor: Colors.white,
                ),
                child: const Text("Login"),
              ),
            ),
            const SizedBox(height: 16),
            SizedBox(
              width: double.infinity,
              height: 50,
              child: OutlinedButton(
                onPressed: () => Navigator.pushNamed(context, '/register'),
                child: const Text("Create Account"),
              ),
            ),
          ],
        ),
      ),
    );
  }
}